language: node_js
node_js:
- lts/*
env:
  global:
    secure: bpmkyDQb/CWlH4/dnVckWk+aPpTIqdSi4oPzXhRs8pEYIwhUAxmcX84gpeM51uYsZztQdvfct3JW05XsrvyfJEdFKjLai23fabY3CZiFyxKwfbs06wiknIUKDG1uwi6Ud5A+wpOikhSiZIneFzDkpehpqmsLgXvtj4QMCYvriu0hUSvqNItgUU4MfrZqii42xk9NuTDxcHCvp7oOWNGzIlw0eYdVN99aQhETfBBDjF4cSStn05Myh3/TWqs8MMeJ/8dKpBIa9spaDuveKEh4MFO6GOTTmTKvU8eeUnWj0hFm53GUsUK6XeOX8yiQNOGOsRqDjl9iiMgQts8czIKjMbdGRMt+MKNles9xPQ22LUW/FkoNarghNrgNgMdrMii61GQ0pGtSInHUqe2dpZkjuQmNBlRV9Rpp6/uKGsACSWDn5V/IJ2XvgTv7w84RUE0Jn7axDhWj2sUSAyBV6rriyQ8Phdksw013UC1hJZW8zvca8gEXLuw3Qw2HkEeD0bNqbxAtuV4sxue6OvCrwL6m2BhxGYTMLCLLigVU3W8SsAF2f+XZVDlJl+NADTDVnsRfZdFuMuPKUrqy673Tayk5bAjmiQhCqvZzkgNB5srYfrHX78+VbokhnzhBC4F9vEC3+77OSF6OudqYj3R8CIYAInra4EGr6g0vw+6VMXqz4Ps=
